# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 14.x]
        test_number:
          - 1
          - 2

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm install
    - run: make test-coverage-${{ matrix.test_number }}
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.0
      env:
          NODE_COVERALLS_DEBUG: 1
      with:
          github-token: ${{ secrets.github_token }}
          parallel: true
          flag-name: run-${{ matrix.test_number }}

  finish:
     runs-on: ubuntu-latest
     steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
    
