name: Dependency Review

on:
  pull_request:
    branches:
      - master
      - support/SDK-V3
      - feature/**
      - bugfix/**
      - dependabot/**
      - feature/security-workflows
  push:
    branches:
      - master
      - support/SDK-V3
      - feature/**
      - bugfix/**
      - dependabot/**
      - feature/security-workflows
  workflow_dispatch:

jobs:
  dependency-review:
    uses: hyperwallet/security-workflows/.github/workflows/dependency-review.yml@main
